# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200)),
                ('last_update', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
